FROM node:24-slim
WORKDIR /app
COPY package.json ./
RUN echo '{"name": "placeholder", "version": "1.0.0"}' > package.json && \
    echo 'const http = require("http"); const server = http.createServer((req, res) => { res.writeHead(200); res.end("Blog placeholder - infrastructure deployed!"); }); server.listen(3000, "0.0.0.0", () => console.log("Server running on port 3000"));' > server.js
EXPOSE 3000
CMD ["node", "server.js"]
