<script setup lang="ts">
definePageMeta({ layout: 'reading' });

const route = useRoute();
const router = useRouter();

const sections = [
  'stories',
  'reading-modes',
  'phonics-slider',
  'practice-cards',
  'curriculum',
  'how-it-works',
] as const;

const initialSection = sections.includes(route.query.section as (typeof sections)[number])
  ? (route.query.section as string)
  : '';
const expandedSection = ref(initialSection);

function toggleSection(id: string) {
  expandedSection.value = expandedSection.value === id ? '' : id;
}

watch(expandedSection, (val) => {
  router.replace({ query: { ...route.query, section: val || undefined } });
});
</script>

<template>
  <div class="max-w-3xl mx-auto px-4 pb-12 pt-8 space-y-8">
    <!-- Header -->
    <div class="text-center space-y-3 reading-float-in">
      <div class="text-5xl">📚</div>
      <h1
        class="text-4xl md:text-5xl font-extrabold text-[var(--reading-text)]"
        style="font-family: var(--reading-font-display)"
      >
        About the Reading App
      </h1>
      <p class="text-lg text-[var(--reading-text)]/60 max-w-xl mx-auto">
        An AI-powered reading practice tool designed for children ages 5-10 who are learning to
        read.
      </p>
    </div>

    <!-- Quick links -->
    <div class="flex flex-wrap gap-2 justify-center">
      <NuxtLink
        to="/reading/demo"
        class="rounded-full px-5 py-2.5 text-sm font-bold bg-[var(--reading-accent)] text-white active:scale-95 transition-all"
        style="font-family: var(--reading-font-display)"
      >
        Try the Demo
      </NuxtLink>
      <NuxtLink
        to="/reading/curriculum"
        class="rounded-full px-5 py-2.5 text-sm font-bold border-2 border-[var(--reading-primary)] text-[var(--reading-primary)] active:scale-95 transition-all"
        style="font-family: var(--reading-font-display)"
      >
        View Curriculum
      </NuxtLink>
    </div>

    <!-- Feature sections -->
    <div class="space-y-4">
      <!-- Personalized Stories -->
      <div
        class="rounded-3xl border-2 border-[var(--reading-primary)]/15 bg-[var(--reading-card-bg)] overflow-hidden shadow-sm"
      >
        <button
          class="w-full flex items-center gap-4 p-5 text-left active:scale-[0.99] transition-all"
          @click="toggleSection('stories')"
        >
          <span class="text-3xl">📖</span>
          <div class="flex-1">
            <h2
              class="text-xl font-bold text-[var(--reading-text)]"
              style="font-family: var(--reading-font-display)"
            >
              Personalized Stories
            </h2>
            <p class="text-sm text-[var(--reading-text)]/50">
              AI-generated decodable stories matched to your child's level
            </p>
          </div>
          <span
            class="text-[var(--reading-primary)] text-xl transition-transform"
            :class="expandedSection === 'stories' ? 'rotate-180' : ''"
          >
            &#x25BC;
          </span>
        </button>
        <div v-if="expandedSection === 'stories'" class="px-5 pb-5 space-y-3 reading-float-in">
          <p class="text-base text-[var(--reading-text)]/80">
            Every story is generated by AI (Claude Haiku) using
            <strong>only words your child can actually read</strong>. The app tracks which phonics
            patterns your child has mastered and constrains the story to those patterns plus
            age-appropriate sight words.
          </p>
          <div class="rounded-2xl bg-[var(--reading-bg)] p-4 space-y-2">
            <p class="text-sm font-bold text-[var(--reading-text)]/60">How story creation works:</p>
            <ul class="text-sm text-[var(--reading-text)]/70 space-y-1.5 list-none">
              <li>&#x2728; Pick a genre (animals, adventure, space, etc.) or leave it blank</li>
              <li>&#x1F9D1; Optionally name a main character</li>
              <li>&#x1F4A1; Optionally describe a story idea</li>
              <li>&#x1F3B2; Or just tap "Surprise Me!" for a random story</li>
              <li>&#x1F3A8; Each story gets AI-generated illustrations (Google Gemini)</li>
            </ul>
          </div>
          <p class="text-sm text-[var(--reading-text)]/50">
            Stories are ~75 words with a simple problem-attempt-resolution arc. A decodability score
            shows what percentage of words match your child's known patterns.
          </p>
        </div>
      </div>

      <!-- Reading Modes -->
      <div
        class="rounded-3xl border-2 border-[var(--reading-accent)]/15 bg-[var(--reading-card-bg)] overflow-hidden shadow-sm"
      >
        <button
          class="w-full flex items-center gap-4 p-5 text-left active:scale-[0.99] transition-all"
          @click="toggleSection('reading-modes')"
        >
          <span class="text-3xl">&#x1F3A7;</span>
          <div class="flex-1">
            <h2
              class="text-xl font-bold text-[var(--reading-text)]"
              style="font-family: var(--reading-font-display)"
            >
              4 Reading Modes
            </h2>
            <p class="text-sm text-[var(--reading-text)]/50">
              Listen, Read Aloud, Read Alone, and Read Together
            </p>
          </div>
          <span
            class="text-[var(--reading-accent)] text-xl transition-transform"
            :class="expandedSection === 'reading-modes' ? 'rotate-180' : ''"
          >
            &#x25BC;
          </span>
        </button>
        <div
          v-if="expandedSection === 'reading-modes'"
          class="px-5 pb-5 space-y-3 reading-float-in"
        >
          <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div class="rounded-2xl bg-[var(--reading-bg)] p-4">
              <p
                class="font-bold text-[var(--reading-primary)] mb-1"
                style="font-family: var(--reading-font-display)"
              >
                &#x1F50A; Listen
              </p>
              <p class="text-sm text-[var(--reading-text)]/70">
                The app reads the story aloud with word-by-word highlighting. Tap any word to hear
                it again. Adjustable speed control.
              </p>
            </div>
            <div class="rounded-2xl bg-[var(--reading-bg)] p-4">
              <p
                class="font-bold text-[var(--reading-accent)] mb-1"
                style="font-family: var(--reading-font-display)"
              >
                &#x1F3A4; Read Aloud
              </p>
              <p class="text-sm text-[var(--reading-text)]/70">
                Your child reads aloud while the app listens via speech recognition. Words highlight
                green (correct) or red (needs practice). Tracks miscues and reading speed (WCPM).
              </p>
            </div>
            <div class="rounded-2xl bg-[var(--reading-bg)] p-4">
              <p
                class="font-bold text-[var(--reading-success)] mb-1"
                style="font-family: var(--reading-font-display)"
              >
                &#x1F440; Read Alone
              </p>
              <p class="text-sm text-[var(--reading-text)]/70">
                Independent reading with no audio. Tap any word to hear its pronunciation. Navigate
                pages at your own pace.
              </p>
            </div>
            <div class="rounded-2xl bg-[var(--reading-bg)] p-4">
              <p
                class="font-bold text-[var(--reading-secondary)] mb-1"
                style="font-family: var(--reading-font-display)"
              >
                &#x1F91D; Read Together
              </p>
              <p class="text-sm text-[var(--reading-text)]/70">
                Parent and child take turns reading alternating pages. The parent reads odd pages,
                the child reads even pages with speech recognition support.
              </p>
            </div>
          </div>
        </div>
      </div>

      <!-- Phonics Slider -->
      <div
        class="rounded-3xl border-2 border-[var(--reading-success)]/15 bg-[var(--reading-card-bg)] overflow-hidden shadow-sm"
      >
        <button
          class="w-full flex items-center gap-4 p-5 text-left active:scale-[0.99] transition-all"
          @click="toggleSection('phonics-slider')"
        >
          <span class="text-3xl">&#x1F524;</span>
          <div class="flex-1">
            <h2
              class="text-xl font-bold text-[var(--reading-text)]"
              style="font-family: var(--reading-font-display)"
            >
              Sound-Out Slider
            </h2>
            <p class="text-sm text-[var(--reading-text)]/50">
              Drag through phonics segments to sound out words
            </p>
          </div>
          <span
            class="text-[var(--reading-success)] text-xl transition-transform"
            :class="expandedSection === 'phonics-slider' ? 'rotate-180' : ''"
          >
            &#x25BC;
          </span>
        </button>
        <div
          v-if="expandedSection === 'phonics-slider'"
          class="px-5 pb-5 space-y-3 reading-float-in"
        >
          <p class="text-base text-[var(--reading-text)]/80">
            When reading a story, tap any decodable word to open the phonics slider. The word splits
            into its phonics segments and you drag across them to hear each sound.
          </p>
          <div class="rounded-2xl bg-[var(--reading-bg)] p-4 space-y-2">
            <p class="text-sm font-bold text-[var(--reading-text)]/60">Example: "ship"</p>
            <div class="flex items-center gap-1 justify-center">
              <span
                class="px-4 py-2 rounded-lg bg-[var(--reading-success)] text-white font-bold text-lg"
                style="font-family: var(--reading-font-display)"
                >sh</span
              >
              <span
                class="px-4 py-2 rounded-lg bg-[var(--reading-accent)] text-white font-bold text-lg"
                style="font-family: var(--reading-font-display)"
                >i</span
              >
              <span
                class="px-4 py-2 rounded-lg bg-[var(--reading-primary)]/15 text-[var(--reading-text)] font-bold text-lg"
                style="font-family: var(--reading-font-display)"
                >p</span
              >
            </div>
            <p class="text-xs text-[var(--reading-text)]/50 text-center">
              Digraph "sh" stays together &#x2022; Each segment speaks its phoneme sound
            </p>
          </div>
          <p class="text-sm text-[var(--reading-text)]/50">
            The slider understands CVC patterns, digraphs, blends, vowel teams, and silent-e
            patterns. Sight words just speak the whole word. The slider can be toggled off in the
            reader controls.
          </p>
        </div>
      </div>

      <!-- Practice Cards -->
      <div
        class="rounded-3xl border-2 border-[var(--reading-highlight)]/30 bg-[var(--reading-card-bg)] overflow-hidden shadow-sm"
      >
        <button
          class="w-full flex items-center gap-4 p-5 text-left active:scale-[0.99] transition-all"
          @click="toggleSection('practice-cards')"
        >
          <span class="text-3xl">&#x1F3B4;</span>
          <div class="flex-1">
            <h2
              class="text-xl font-bold text-[var(--reading-text)]"
              style="font-family: var(--reading-font-display)"
            >
              Spaced Repetition Cards
            </h2>
            <p class="text-sm text-[var(--reading-text)]/50">
              Science-backed flashcards for phonics and sight words
            </p>
          </div>
          <span
            class="text-[var(--reading-highlight)] text-xl transition-transform"
            :class="expandedSection === 'practice-cards' ? 'rotate-180' : ''"
          >
            &#x25BC;
          </span>
        </button>
        <div
          v-if="expandedSection === 'practice-cards'"
          class="px-5 pb-5 space-y-3 reading-float-in"
        >
          <p class="text-base text-[var(--reading-text)]/80">
            Practice cards use the <strong>FSRS algorithm</strong> (the same one used by Anki) to
            schedule reviews at optimal intervals. Cards that are harder come back sooner; cards
            your child knows well space out over days or weeks.
          </p>
          <div class="rounded-2xl bg-[var(--reading-bg)] p-4 space-y-2">
            <p class="text-sm font-bold text-[var(--reading-text)]/60">Card types:</p>
            <ul class="text-sm text-[var(--reading-text)]/70 space-y-1 list-none">
              <li>
                &#x1F524; <strong>Phoneme cards</strong> — practice individual sounds and patterns
              </li>
              <li>
                &#x1F440; <strong>Sight word cards</strong> — high-frequency words to recognize on
                sight
              </li>
              <li>
                &#x1F4D6; <strong>Vocabulary cards</strong> — new words encountered in stories
              </li>
            </ul>
          </div>
          <p class="text-sm text-[var(--reading-text)]/50">
            After seeing a card, rate it "Again" (forgot), "Hard" (struggled), or "Got It!" (easy).
            The algorithm adjusts the next review date accordingly. Words with stability > 10 and 3+
            reviews appear in your Word Treasure collection.
          </p>
        </div>
      </div>

      <!-- Curriculum -->
      <div
        class="rounded-3xl border-2 border-[var(--reading-secondary)]/15 bg-[var(--reading-card-bg)] overflow-hidden shadow-sm"
      >
        <button
          class="w-full flex items-center gap-4 p-5 text-left active:scale-[0.99] transition-all"
          @click="toggleSection('curriculum')"
        >
          <span class="text-3xl">&#x1F331;</span>
          <div class="flex-1">
            <h2
              class="text-xl font-bold text-[var(--reading-text)]"
              style="font-family: var(--reading-font-display)"
            >
              Phonics Curriculum
            </h2>
            <p class="text-sm text-[var(--reading-text)]/50">
              4 phases from letter sounds to advanced decoding
            </p>
          </div>
          <span
            class="text-[var(--reading-secondary)] text-xl transition-transform"
            :class="expandedSection === 'curriculum' ? 'rotate-180' : ''"
          >
            &#x25BC;
          </span>
        </button>
        <div v-if="expandedSection === 'curriculum'" class="px-5 pb-5 space-y-3 reading-float-in">
          <p class="text-base text-[var(--reading-text)]/80">
            The reading app follows a structured phonics progression across 4 phases. Children start
            at Phase 1 and advance as they master each unit.
          </p>
          <div class="space-y-2">
            <div class="rounded-2xl bg-[var(--reading-bg)] p-3 flex items-start gap-3">
              <span class="text-2xl">&#x1F331;</span>
              <div>
                <p
                  class="font-bold text-sm text-[var(--reading-text)]"
                  style="font-family: var(--reading-font-display)"
                >
                  Phase 1: Foundations
                </p>
                <p class="text-xs text-[var(--reading-text)]/60">
                  Single consonants, CVC short vowels (cat, sit, hop), digraphs (sh, th, ch)
                </p>
              </div>
            </div>
            <div class="rounded-2xl bg-[var(--reading-bg)] p-3 flex items-start gap-3">
              <span class="text-2xl">&#x1F333;</span>
              <div>
                <p
                  class="font-bold text-sm text-[var(--reading-text)]"
                  style="font-family: var(--reading-font-display)"
                >
                  Phase 2: Building Complexity
                </p>
                <p class="text-xs text-[var(--reading-text)]/60">
                  Blends (st, cr, bl), silent-e (cake, bike), FLOSS rule, open syllables
                </p>
              </div>
            </div>
            <div class="rounded-2xl bg-[var(--reading-bg)] p-3 flex items-start gap-3">
              <span class="text-2xl">&#x1F308;</span>
              <div>
                <p
                  class="font-bold text-sm text-[var(--reading-text)]"
                  style="font-family: var(--reading-font-display)"
                >
                  Phase 3: Intermediate Patterns
                </p>
                <p class="text-xs text-[var(--reading-text)]/60">
                  Vowel teams (ai, ee, oa), r-controlled vowels (ar, or, er), diphthongs, silent
                  letters
                </p>
              </div>
            </div>
            <div class="rounded-2xl bg-[var(--reading-bg)] p-3 flex items-start gap-3">
              <span class="text-2xl">&#x1F680;</span>
              <div>
                <p
                  class="font-bold text-sm text-[var(--reading-text)]"
                  style="font-family: var(--reading-font-display)"
                >
                  Phase 4: Advanced Decoding
                </p>
                <p class="text-xs text-[var(--reading-text)]/60">
                  Hard/soft c and g, syllable division, affixes (-ed, -ing, un-), Latin/Greek roots
                </p>
              </div>
            </div>
          </div>
          <NuxtLink
            to="/reading/curriculum"
            class="inline-block text-sm font-bold text-[var(--reading-primary)] mt-1"
          >
            View full curriculum details &#x2192;
          </NuxtLink>
        </div>
      </div>

      <!-- How It Works (Tech) -->
      <div
        class="rounded-3xl border-2 border-[var(--reading-text)]/10 bg-[var(--reading-card-bg)] overflow-hidden shadow-sm"
      >
        <button
          class="w-full flex items-center gap-4 p-5 text-left active:scale-[0.99] transition-all"
          @click="toggleSection('how-it-works')"
        >
          <span class="text-3xl">&#x2699;&#xFE0F;</span>
          <div class="flex-1">
            <h2
              class="text-xl font-bold text-[var(--reading-text)]"
              style="font-family: var(--reading-font-display)"
            >
              How It Works
            </h2>
            <p class="text-sm text-[var(--reading-text)]/50">
              The technology behind the reading app
            </p>
          </div>
          <span
            class="text-[var(--reading-text)]/40 text-xl transition-transform"
            :class="expandedSection === 'how-it-works' ? 'rotate-180' : ''"
          >
            &#x25BC;
          </span>
        </button>
        <div v-if="expandedSection === 'how-it-works'" class="px-5 pb-5 space-y-3 reading-float-in">
          <div class="space-y-2">
            <div class="rounded-2xl bg-[var(--reading-bg)] p-4">
              <p class="font-bold text-sm text-[var(--reading-text)] mb-1">Story Generation</p>
              <p class="text-sm text-[var(--reading-text)]/70">
                Claude Haiku generates decodable stories constrained to your child's known phonics
                patterns and sight words. Each story targets 95%+ decodability, meaning nearly every
                word is one your child can sound out.
              </p>
            </div>
            <div class="rounded-2xl bg-[var(--reading-bg)] p-4">
              <p class="font-bold text-sm text-[var(--reading-text)] mb-1">Illustrations</p>
              <p class="text-sm text-[var(--reading-text)]/70">
                Google Gemini generates unique illustrations for each page in a consistent
                Bluey/Peppa Pig-inspired art style. Characters are recognized across pages for
                visual consistency.
              </p>
            </div>
            <div class="rounded-2xl bg-[var(--reading-bg)] p-4">
              <p class="font-bold text-sm text-[var(--reading-text)] mb-1">Speech Recognition</p>
              <p class="text-sm text-[var(--reading-text)]/70">
                The Web Speech API listens to your child read aloud and compares spoken words to the
                expected text. It tracks miscues (omissions, insertions, substitutions) and
                calculates words correct per minute (WCPM).
              </p>
            </div>
            <div class="rounded-2xl bg-[var(--reading-bg)] p-4">
              <p class="font-bold text-sm text-[var(--reading-text)] mb-1">Text-to-Speech</p>
              <p class="text-sm text-[var(--reading-text)]/70">
                The Web Speech API reads stories aloud with word-by-word highlighting at a
                child-friendly pace (0.8x default speed, adjustable). Individual words can be tapped
                to hear pronunciation.
              </p>
            </div>
            <div class="rounded-2xl bg-[var(--reading-bg)] p-4">
              <p class="font-bold text-sm text-[var(--reading-text)] mb-1">Spaced Repetition</p>
              <p class="text-sm text-[var(--reading-text)]/70">
                The FSRS algorithm (ts-fsrs library) schedules card reviews for optimal long-term
                retention with 85% target retention rate and up to 180-day intervals for well-known
                material.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Footer CTA -->
    <div class="text-center space-y-4 pt-4">
      <p
        class="text-lg text-[var(--reading-text)]/50"
        style="font-family: var(--reading-font-display)"
      >
        Ready to get started?
      </p>
      <div class="flex flex-col sm:flex-row gap-3 justify-center">
        <NuxtLink
          to="/reading/demo"
          class="rounded-full px-8 py-3 text-base font-bold bg-[var(--reading-accent)] text-white active:scale-95 transition-all shadow-md"
          style="font-family: var(--reading-font-display)"
        >
          Try a Demo Story
        </NuxtLink>
        <NuxtLink
          to="/reading/onboarding"
          class="rounded-full px-8 py-3 text-base font-bold border-2 border-[var(--reading-primary)] text-[var(--reading-primary)] active:scale-95 transition-all"
          style="font-family: var(--reading-font-display)"
        >
          Create an Account
        </NuxtLink>
      </div>
    </div>
  </div>
</template>
