import { z } from 'zod';

defineRouteMeta({
  openAPI: {
    description: 'Download a file generated by artifact code execution from Anthropic Files API.',
    tags: ['artifacts'],
  },
});

export default defineEventHandler(async (event) => {
  const { id } = await getValidatedRouterParams(
    event,
    z.object({
      id: z.string().min(1),
    }).parse,
  );

  try {
    const client = getAnthropicClient();

    // Download the file content via Anthropic Files API
    const fileResponse = await (client as any).beta.files.download(id, {
      betas: ['files-api-2025-04-14'],
    });

    // Get file metadata for content-type
    const fileMeta = await (client as any).beta.files.retrieve(id, {
      betas: ['files-api-2025-04-14'],
    });

    const contentType = fileMeta?.mime_type || 'application/octet-stream';
    const fileName = fileMeta?.filename || 'download';

    setHeader(event, 'Content-Type', contentType);
    setHeader(event, 'Content-Disposition', `inline; filename="${fileName}"`);
    setHeader(event, 'Cache-Control', 'public, max-age=86400');

    // fileResponse is a Response-like object, extract the body
    if (fileResponse instanceof Response) {
      return fileResponse.body;
    }

    // If it's a buffer/ArrayBuffer
    if (fileResponse instanceof ArrayBuffer || ArrayBuffer.isView(fileResponse)) {
      return new Uint8Array(
        fileResponse instanceof ArrayBuffer ? fileResponse : fileResponse.buffer,
      );
    }

    // If it's a readable stream
    if (typeof fileResponse.body?.getReader === 'function') {
      return fileResponse.body;
    }

    // Fallback: return as-is
    return fileResponse;
  } catch (err) {
    console.error('File download error:', err);
    throw createError({
      statusCode: 404,
      statusMessage: 'File not found or expired',
    });
  }
});
