import { z } from 'zod';
import { log } from 'evlog';

defineRouteMeta({
  openAPI: {
    description: 'Download a file generated by artifact code execution from Anthropic Files API.',
    tags: ['artifacts'],
  },
});

export default defineEventHandler(async (event) => {
  await getUserSession(event);

  const { id } = await getValidatedRouterParams(
    event,
    z.object({
      id: z.string().min(1),
    }).parse,
  );

  try {
    const client = getAnthropicClient();

    // Download file content and metadata in parallel
    const [fileResponse, fileMeta] = await Promise.all([
      client.beta.files.download(id, {
        betas: ['files-api-2025-04-14'],
      }),
      client.beta.files.retrieveMetadata(id, {
        betas: ['files-api-2025-04-14'],
      }),
    ]);

    const contentType = fileMeta?.mime_type || 'application/octet-stream';
    const fileName = fileMeta?.filename || 'download';

    setHeader(event, 'Content-Type', contentType);
    setHeader(event, 'Content-Disposition', `inline; filename="${fileName}"`);
    setHeader(event, 'Cache-Control', 'public, max-age=86400');

    return fileResponse.body;
  } catch {
    log.error('artifact', 'File download error');
    throw createError({
      statusCode: 404,
      statusMessage: 'File not found or expired',
    });
  }
});
