import { z } from 'zod';
import type { AnthropicBetaClient } from '~~/server/utils/ai/anthropic-beta-types';

defineRouteMeta({
  openAPI: {
    description: 'Download a file generated by artifact code execution from Anthropic Files API.',
    tags: ['artifacts'],
  },
});

export default defineEventHandler(async (event) => {
  await getUserSession(event);

  const { id } = await getValidatedRouterParams(
    event,
    z.object({
      id: z.string().min(1),
    }).parse,
  );

  try {
    const client = getAnthropicClient();

    // Download file content and metadata in parallel
    const betaClient = client as unknown as AnthropicBetaClient;
    const [fileResponse, fileMeta] = await Promise.all([
      betaClient.beta.files.download(id, {
        betas: ['files-api-2025-04-14'],
      }),
      betaClient.beta.files.retrieveMetadata(id, {
        betas: ['files-api-2025-04-14'],
      }),
    ]);

    const contentType = fileMeta?.mime_type || 'application/octet-stream';
    const fileName = fileMeta?.filename || 'download';

    setHeader(event, 'Content-Type', contentType);
    setHeader(event, 'Content-Disposition', `inline; filename="${fileName}"`);
    setHeader(event, 'Cache-Control', 'public, max-age=86400');

    // Extract the streamable body from whichever response shape the SDK returns
    if (fileResponse instanceof Response) {
      return fileResponse.body;
    }
    if (fileResponse instanceof ArrayBuffer) {
      return new Uint8Array(fileResponse);
    }
    if (ArrayBuffer.isView(fileResponse)) {
      return new Uint8Array(fileResponse.buffer);
    }
    // Response-like object with a readable body (StreamableResponse)
    if (fileResponse.body) {
      return fileResponse.body;
    }
    return fileResponse;
  } catch (err) {
    console.error('File download error:', err);
    throw createError({
      statusCode: 404,
      statusMessage: 'File not found or expired',
    });
  }
});
