import type { PhonicsPhase } from '../../../shared/reading-types';

export interface PhonicsUnitSeed {
  phase: PhonicsPhase;
  orderIndex: number;
  name: string;
  patterns: string[];
  description: string;
}

export const PHONICS_SEED: PhonicsUnitSeed[] = [
  // Phase 1: Foundations
  {
    phase: 1,
    orderIndex: 1,
    name: 'Single consonants (b, c, d, f, g, h)',
    patterns: ['C-b', 'C-c', 'C-d', 'C-f', 'C-g', 'C-h'],
    description: 'Initial consonant sounds: b, c, d, f, g, h',
  },
  {
    phase: 1,
    orderIndex: 2,
    name: 'Single consonants (k, l, m, n, p, s, t)',
    patterns: ['C-k', 'C-l', 'C-m', 'C-n', 'C-p', 'C-s', 'C-t'],
    description: 'Initial consonant sounds: k, l, m, n, p, s, t',
  },
  {
    phase: 1,
    orderIndex: 3,
    name: 'CVC short-a',
    patterns: ['CVC-short-a'],
    description: 'Consonant-vowel-consonant words with short a (cat, hat, man)',
  },
  {
    phase: 1,
    orderIndex: 4,
    name: 'CVC short-i',
    patterns: ['CVC-short-i'],
    description: 'CVC words with short i (sit, hit, pin)',
  },
  {
    phase: 1,
    orderIndex: 5,
    name: 'CVC short-o',
    patterns: ['CVC-short-o'],
    description: 'CVC words with short o (hot, dog, mop)',
  },
  {
    phase: 1,
    orderIndex: 6,
    name: 'CVC short-u',
    patterns: ['CVC-short-u'],
    description: 'CVC words with short u (cup, bug, sun)',
  },
  {
    phase: 1,
    orderIndex: 7,
    name: 'CVC short-e',
    patterns: ['CVC-short-e'],
    description: 'CVC words with short e (bed, red, pet)',
  },
  {
    phase: 1,
    orderIndex: 8,
    name: 'Digraphs sh, th, ch',
    patterns: ['DG-sh', 'DG-th', 'DG-ch'],
    description: 'Consonant digraphs: sh (ship), th (thin), ch (chop)',
  },
  {
    phase: 1,
    orderIndex: 9,
    name: 'Digraph ck and remaining consonants',
    patterns: ['DG-ck', 'C-j', 'C-r', 'C-v', 'C-w', 'C-x', 'C-y', 'C-z', 'C-qu'],
    description: 'Digraph ck (back) and consonants j, r, v, w, x, y, z, qu',
  },

  // Phase 2: Building complexity
  {
    phase: 2,
    orderIndex: 1,
    name: 'Initial consonant blends',
    patterns: [
      'BL-bl',
      'BL-cr',
      'BL-st',
      'BL-fl',
      'BL-gr',
      'BL-tr',
      'BL-br',
      'BL-cl',
      'BL-dr',
      'BL-fr',
      'BL-gl',
      'BL-pl',
      'BL-pr',
      'BL-sk',
      'BL-sl',
      'BL-sm',
      'BL-sn',
      'BL-sp',
      'BL-sw',
    ],
    description:
      'Initial blends: bl, cr, st, fl, gr, tr, br, cl, dr, fr, gl, pl, pr, sk, sl, sm, sn, sp, sw',
  },
  {
    phase: 2,
    orderIndex: 2,
    name: 'Final consonant blends',
    patterns: [
      'BL-mp',
      'BL-nk',
      'BL-nd',
      'BL-nt',
      'BL-ft',
      'BL-lt',
      'BL-lp',
      'BL-lk',
      'BL-sk-f',
      'BL-st-f',
    ],
    description: 'Final blends: -mp, -nk, -nd, -nt, -ft, -lt, -lp, -lk, -sk, -st',
  },
  {
    phase: 2,
    orderIndex: 3,
    name: 'FLOSS rule',
    patterns: ['FLOSS-ff', 'FLOSS-ll', 'FLOSS-ss'],
    description: 'Double final consonants after short vowels: ff (puff), ll (bell), ss (miss)',
  },
  {
    phase: 2,
    orderIndex: 4,
    name: 'Silent-e / VCe long vowels',
    patterns: ['VCe-a', 'VCe-i', 'VCe-o', 'VCe-u', 'VCe-e'],
    description: 'Magic e pattern: bake, ride, bone, cute, theme',
  },
  {
    phase: 2,
    orderIndex: 5,
    name: 'Open syllables',
    patterns: ['OPEN-a', 'OPEN-e', 'OPEN-i', 'OPEN-o', 'OPEN-u'],
    description: 'Open syllables ending in vowel: he, my, no, go, be',
  },

  // Phase 3: Intermediate patterns
  {
    phase: 3,
    orderIndex: 1,
    name: 'Vowel teams ai/ay, ee/ea',
    patterns: ['VT-ai', 'VT-ay', 'VT-ee', 'VT-ea'],
    description: 'Vowel teams: ai (rain), ay (day), ee (tree), ea (read)',
  },
  {
    phase: 3,
    orderIndex: 2,
    name: 'Vowel teams oa/oe, oo, ou/ow',
    patterns: ['VT-oa', 'VT-oe', 'VT-oo', 'VT-ou', 'VT-ow'],
    description: 'Vowel teams: oa (boat), oe (toe), oo (moon/book), ou (out), ow (cow/snow)',
  },
  {
    phase: 3,
    orderIndex: 3,
    name: 'R-controlled vowels',
    patterns: ['RC-ar', 'RC-or', 'RC-er', 'RC-ir', 'RC-ur'],
    description: 'R-controlled: ar (car), or (for), er (her), ir (bird), ur (burn)',
  },
  {
    phase: 3,
    orderIndex: 4,
    name: 'Diphthongs oi/oy, ou/ow',
    patterns: ['DI-oi', 'DI-oy', 'DI-ou', 'DI-ow'],
    description: 'Diphthongs: oi (coin), oy (boy), ou (loud), ow (cow)',
  },
  {
    phase: 3,
    orderIndex: 5,
    name: 'Silent letters',
    patterns: ['SL-kn', 'SL-wr', 'SL-mb', 'SL-igh'],
    description: 'Silent letters: kn (knot), wr (write), mb (lamb), igh (night)',
  },

  // Phase 4: Advanced decoding
  {
    phase: 4,
    orderIndex: 1,
    name: 'Hard and soft c and g',
    patterns: ['HS-c-hard', 'HS-c-soft', 'HS-g-hard', 'HS-g-soft'],
    description: 'Hard/soft: c as /k/ (cat) vs /s/ (city), g as /g/ (go) vs /j/ (gem)',
  },
  {
    phase: 4,
    orderIndex: 2,
    name: 'Syllable division',
    patterns: ['SYL-VCCV', 'SYL-VCV', 'SYL-VCCCV', 'SYL-VV'],
    description: 'Syllable division rules: VCCV (rabbit), VCV (tiger), VCCCV (pumpkin)',
  },
  {
    phase: 4,
    orderIndex: 3,
    name: 'Common prefixes and suffixes',
    patterns: [
      'AFF-ed',
      'AFF-ing',
      'AFF-re',
      'AFF-un',
      'AFF-tion',
      'AFF-ly',
      'AFF-ful',
      'AFF-less',
    ],
    description: 'Affixes: -ed, -ing, re-, un-, -tion, -ly, -ful, -less',
  },
  {
    phase: 4,
    orderIndex: 4,
    name: 'Latin and Greek roots',
    patterns: ['ROOT-latin', 'ROOT-greek'],
    description: 'Common Latin/Greek roots and their meanings',
  },
];

// Common sight words by phase (high-frequency words that don't follow phonics rules)
export const SIGHT_WORDS_BY_PHASE: Record<PhonicsPhase, string[]> = {
  1: [
    'the',
    'a',
    'is',
    'was',
    'to',
    'and',
    'he',
    'she',
    'said',
    'my',
    'of',
    'I',
    'you',
    'are',
    'they',
    'we',
    'do',
    'no',
    'go',
    'so',
  ],
  2: [
    'have',
    'were',
    'what',
    'when',
    'your',
    'there',
    'their',
    'would',
    'could',
    'should',
    'come',
    'some',
    'one',
    'two',
    'who',
    'been',
    'from',
    'many',
    'any',
    'again',
  ],
  3: [
    'through',
    'thought',
    'because',
    'enough',
    'though',
    'people',
    'where',
    'friend',
    'know',
    'world',
    'great',
    'heart',
    'different',
    'move',
    'water',
    'every',
    'other',
    'laugh',
    'answer',
    'learn',
  ],
  4: [
    'knowledge',
    'science',
    'special',
    'certain',
    'beautiful',
    'imagine',
    'important',
    'language',
    'measure',
    'machine',
    'believe',
    'receive',
    'separate',
    'rhythm',
    'necessary',
  ],
};
