/**
 * Shared types for the artifact/code execution system.
 * Uses Anthropic's Code Execution Tool, Files API, and Skills API
 * to run code in isolated containers on Anthropic's infrastructure.
 */

/** Status of an artifact execution */
export type ArtifactStatus = 'idle' | 'executing' | 'streaming' | 'complete' | 'error';

/** A file generated by code execution in the container */
export interface ArtifactFile {
  fileId: string;
  fileName: string;
  mediaType: string;
  /** URL to download via our proxy: /api/artifacts/files/{fileId} */
  url: string;
}

/** A code execution result from the container */
export interface CodeExecutionResult {
  stdout: string;
  stderr: string;
  exitCode: number;
}

/** Request to execute code in an artifact container */
export interface ArtifactExecuteRequest {
  /** User's prompt describing what to create/modify */
  prompt: string;
  /** Optional initial code to seed the container with */
  code?: string;
  /** Language hint for the code (python, bash, etc.) */
  language?: string;
  /** Reuse an existing container for multi-turn editing */
  containerId?: string;
  /** Skills to load into the container */
  skills?: ArtifactSkill[];
}

/** Skill configuration for artifact execution */
export interface ArtifactSkill {
  type: 'anthropic' | 'custom';
  skillId: string;
  version?: string;
}

// --- SSE event types for streaming artifact execution ---

export interface ArtifactSSETextEvent {
  type: 'artifact_text';
  text: string;
}

export interface ArtifactSSECodeEvent {
  type: 'artifact_code';
  code: string;
  language?: string;
}

export interface ArtifactSSEExecutionStartEvent {
  type: 'artifact_execution_start';
}

export interface ArtifactSSEExecutionResultEvent {
  type: 'artifact_execution_result';
  stdout: string;
  stderr: string;
  exitCode: number;
}

export interface ArtifactSSEFileEvent {
  type: 'artifact_file';
  file: ArtifactFile;
}

export interface ArtifactSSEContainerEvent {
  type: 'artifact_container';
  containerId: string;
}

export interface ArtifactSSEDoneEvent {
  type: 'artifact_done';
}

export interface ArtifactSSEErrorEvent {
  type: 'artifact_error';
  error: string;
}

export type ArtifactSSEEvent =
  | ArtifactSSETextEvent
  | ArtifactSSECodeEvent
  | ArtifactSSEExecutionStartEvent
  | ArtifactSSEExecutionResultEvent
  | ArtifactSSEFileEvent
  | ArtifactSSEContainerEvent
  | ArtifactSSEDoneEvent
  | ArtifactSSEErrorEvent;
