/**
 * Shared test IDs for E2E tests and UI components
 *
 * Usage in Vue:
 *
 * import { TEST_IDS } from '~~/shared/test-ids'
 *   <div :data-testid="TEST_IDS.CHAT.INPUT">
 *
 * Usage in Playwright:
 *   page.getByTestId(TEST_IDS.CHAT.INPUT)
 */
export const TEST_IDS = {
  CHAT: {
    INPUT: 'chat-input',
    SUBMIT: 'chat-submit',
    QUICK_ACTIONS: 'quick-actions',
    QUICK_ACTION_BUTTON: 'quick-action-button',
    MESSAGE_LIST: 'chat-messages',
    MESSAGE: 'chat-message',
    SIDEBAR: 'chat-sidebar',
    NEW_CHAT_BUTTON: 'new-chat-button',
    DELETE_CHAT_BUTTON: 'delete-chat-button',
    DELETE_ALL_BUTTON: 'delete-all-chats-button',
    STOP_BUTTON: 'stop-generation',
    RELOAD_BUTTON: 'reload-message',
    COPY_BUTTON: 'copy-message',
  },
  BLOG: {
    POST_LIST: 'blog-post-list',
    POST_LIST_SECTION: 'blog-post-list-section',
    POST_CARD: 'blog-post-card',
    POST_LINK: 'blog-post-link',
    POST_CONTENT: 'post-content',
    POST_TITLE: 'post-title',
    POST_META: 'post-metadata',
    PREV_POST: 'prev-post-link',
    NEXT_POST: 'next-post-link',
    PAGE: 'blog-page',
  },
  NAVIGATION: {
    HEADER: 'app-header',
    FOOTER: 'app-footer',
    HOME_LINK: 'nav-home',
    BLOG_LINK: 'nav-blog',
    WORKFLOWS_LINK: 'nav-workflows',
    CHAT_LINK: 'nav-chat',
    USER_MENU: 'user-menu',
    LOGIN_BUTTON: 'login-button',
    THEME_TOGGLE: 'theme-toggle',
    READING_LINK: 'nav-reading',
  },
  SEARCH: {
    PAGE: 'search-page',
    FORM: 'search-form',
    INPUT: 'search-input',
    SUBMIT: 'search-submit',
    RESULTS: 'search-results',
    RESULT_CARD: 'search-result-card',
  },
  LOAN: {
    PAGE: 'loan-page',
    START_BUTTON: 'loan-start-button',
    CHAT_INPUT: 'loan-chat-input',
    CHAT_MESSAGES: 'loan-chat-messages',
    SUBMIT_REVIEW_BUTTON: 'loan-submit-review',
    PROGRESS: 'loan-progress',
    PROGRESS_BAR: 'loan-progress-bar',
    REVIEW_CARD: 'loan-review-card',
    REVIEW_DECISION: 'loan-review-decision',
    OVERALL_RESULT: 'loan-overall-result',
  },
  READING: {
    LANDING_PAGE: 'reading-landing-page',
    LANDING_CTA: 'reading-landing-cta',
    DASHBOARD_PAGE: 'reading-dashboard-page',
    ONBOARDING_PAGE: 'reading-onboarding-page',
    STORY_READER: 'reading-story-reader',
    WORD_HIGHLIGHTER: 'reading-word-highlighter',
    TTS_PLAY: 'reading-tts-play',
    TTS_PAUSE: 'reading-tts-pause',
    TTS_STOP: 'reading-tts-stop',
    CARD_REVIEW: 'reading-card-review',
    CARD_REVEAL: 'reading-card-reveal',
    CARD_RATE_AGAIN: 'reading-card-rate-again',
    CARD_RATE_HARD: 'reading-card-rate-hard',
    CARD_RATE_GOOD: 'reading-card-rate-good',
    NO_CHILD_PROMPT: 'reading-no-child-prompt',
    ONBOARDING_NAME_INPUT: 'reading-onboarding-name',
    ONBOARDING_BIRTH_YEAR_INPUT: 'reading-onboarding-birth-year',
    ONBOARDING_NEXT: 'reading-onboarding-next',
    ONBOARDING_BACK: 'reading-onboarding-back',
    ONBOARDING_SUBMIT: 'reading-onboarding-submit',
    ONBOARDING_INTEREST_CARD: 'reading-onboarding-interest',
    ONBOARDING_TERMS_CHECKBOX: 'reading-onboarding-terms',
    STORY_LIBRARY: 'reading-story-library',
    STORY_CARD: 'reading-story-card',
    STORY_FAVORITE_TOGGLE: 'reading-story-favorite-toggle',
    STORY_FILTER_THEME: 'reading-story-filter-theme',
    STORY_FILTER_FAVORITES: 'reading-story-filter-favorites',
    STORY_GENERATE_BUTTON: 'reading-story-generate-button',
    WORDS_PAGE: 'reading-words-page',
    WORD_CARD: 'reading-word-card',
    WORD_COUNT: 'reading-word-count',
    STREAK_CALENDAR: 'reading-streak-calendar',
    PROGRESS_CHART: 'reading-progress-chart',
    SRS_STATS_SUMMARY: 'reading-srs-stats-summary',
    ACHIEVEMENT_BADGE: 'reading-achievement-badge',
    ACHIEVEMENT_LIST: 'reading-achievement-list',
    ACHIEVEMENT_NEW: 'reading-achievement-new',
    CURRICULUM_PAGE: 'reading-curriculum-page',
    STORY_WIZARD: 'reading-story-wizard',
    STORY_WIZARD_GENRE: 'reading-story-wizard-genre',
    STORY_WIZARD_WHO: 'reading-story-wizard-who',
    STORY_WIZARD_IDEA: 'reading-story-wizard-idea',
    STORY_WIZARD_SURPRISE: 'reading-story-wizard-surprise',
    STORY_WIZARD_SUBMIT: 'reading-story-wizard-submit',
    STORY_PREVIEW_CARD: 'reading-story-preview-card',
  },
  ADMIN: {
    GITHUB_DASHBOARD: 'admin-github-dashboard',
    GITHUB_SUMMARY_CARDS: 'admin-github-summary-cards',
    GITHUB_CHARTS: 'admin-github-charts',
    GITHUB_ISSUES_TABLE: 'admin-github-issues-table',
  },
  SHARED: {
    MODEL_SELECT: 'model-select',
    SEARCH_BUTTON: 'search-button',
    LOADING_INDICATOR: 'loading-indicator',
  },
} as const;

// Type helper to ensure test IDs are used correctly
export type TestId =
  (typeof TEST_IDS)[keyof typeof TEST_IDS][keyof (typeof TEST_IDS)[keyof typeof TEST_IDS]];
