/**
 * Shared test IDs for E2E tests and UI components
 *
 * Usage in Vue:
 *
 * import { TEST_IDS } from '~~/shared/test-ids'
 *   <div :data-testid="TEST_IDS.CHAT.INPUT">
 *
 * Usage in Playwright:
 *   page.getByTestId(TEST_IDS.CHAT.INPUT)
 */
export const TEST_IDS = {
  CHAT: {
    INPUT: 'chat-input',
    SUBMIT: 'chat-submit',
    QUICK_ACTIONS: 'quick-actions',
    QUICK_ACTION_BUTTON: 'quick-action-button',
    MESSAGE_LIST: 'chat-messages',
    MESSAGE: 'chat-message',
    SIDEBAR: 'chat-sidebar',
    NEW_CHAT_BUTTON: 'new-chat-button',
    DELETE_CHAT_BUTTON: 'delete-chat-button',
    DELETE_ALL_BUTTON: 'delete-all-chats-button',
    STOP_BUTTON: 'stop-generation',
    RELOAD_BUTTON: 'reload-message',
    COPY_BUTTON: 'copy-message',
  },
  BLOG: {
    POST_LIST: 'blog-post-list',
    POST_LIST_SECTION: 'blog-post-list-section',
    POST_CARD: 'blog-post-card',
    POST_LINK: 'blog-post-link',
    POST_CONTENT: 'post-content',
    POST_TITLE: 'post-title',
    POST_META: 'post-metadata',
    PREV_POST: 'prev-post-link',
    NEXT_POST: 'next-post-link',
    PAGE: 'blog-page',
  },
  NAVIGATION: {
    HEADER: 'app-header',
    FOOTER: 'app-footer',
    HOME_LINK: 'nav-home',
    BLOG_LINK: 'nav-blog',
    WORKFLOWS_LINK: 'nav-workflows',
    CHAT_LINK: 'nav-chat',
    USER_MENU: 'user-menu',
    LOGIN_BUTTON: 'login-button',
    THEME_TOGGLE: 'theme-toggle',
    TYPING_LINK: 'nav-typing',
    AVIATION_LINK: 'nav-aviation',
    POKER_LINK: 'nav-poker',
  },
  SEARCH: {
    PAGE: 'search-page',
    FORM: 'search-form',
    INPUT: 'search-input',
    SUBMIT: 'search-submit',
    RESULTS: 'search-results',
    RESULT_CARD: 'search-result-card',
  },
  LOAN: {
    PAGE: 'loan-page',
    START_BUTTON: 'loan-start-button',
    CHAT_INPUT: 'loan-chat-input',
    CHAT_MESSAGES: 'loan-chat-messages',
    SUBMIT_REVIEW_BUTTON: 'loan-submit-review',
    PROGRESS: 'loan-progress',
    PROGRESS_BAR: 'loan-progress-bar',
    REVIEW_CARD: 'loan-review-card',
    REVIEW_DECISION: 'loan-review-decision',
    OVERALL_RESULT: 'loan-overall-result',
  },
  TYPING: {
    LANDING_PAGE: 'typing-landing-page',
    LANDING_CTA: 'typing-landing-cta',
    LESSON_PICKER: 'typing-lesson-picker',
    LESSON_CARD: 'typing-lesson-card',
    LESSON_RUNNER: 'typing-lesson-runner',
    LESSON_INPUT: 'typing-lesson-input',
    LESSON_TEXT: 'typing-lesson-text',
    LESSON_COMPLETE: 'typing-lesson-complete',
    WPM_METER: 'typing-wpm-meter',
    ACCURACY_METER: 'typing-accuracy-meter',
    VIRTUAL_KEYBOARD: 'typing-virtual-keyboard',
    VIRTUAL_KEYBOARD_KEY: 'typing-virtual-keyboard-key',
    NEXT_KEY_HIGHLIGHT: 'typing-next-key-highlight',
    HAND_HINT: 'typing-hand-hint',
    STAGE_MAP: 'typing-stage-map',
    STAGE_TILE: 'typing-stage-tile',
    KEY_HEATMAP: 'typing-key-heatmap',
    PROGRESS_PAGE: 'typing-progress-page',
    LEARNER_SWITCHER: 'typing-learner-switcher',
    LEARNER_OPTION: 'typing-learner-option',
    GROUP_PAGE: 'typing-group-page',
    GROUP_LEARNERS_PAGE: 'typing-group-learners-page',
    GROUP_INVITE_LINK: 'typing-group-invite-link',
    GROUP_JOIN_BUTTON: 'typing-group-join-button',
    TOPICS_PAGE: 'typing-topics-page',
    TOPIC_GAME_FORM: 'typing-topic-game-form',
    TOPIC_GAME_SUBMIT: 'typing-topic-game-submit',
    SPELLING_PAGE: 'typing-spelling-page',
    SPELLING_NEW_PAGE: 'typing-spelling-new-page',
    SPELLING_LIST_FORM: 'typing-spelling-list-form',
    SPELLING_IMAGE_DROPZONE: 'typing-spelling-image-dropzone',
    SPELLING_MASTERY_CARD: 'typing-spelling-mastery-card',
    GAME_STAGE: 'typing-game-stage',
    GAME_LETTER_RAIN: 'typing-game-letter-rain',
    GAME_TIC_TAC_TOE: 'typing-game-tic-tac-toe',
    GAME_LAKE_LEAP: 'typing-game-lake-leap',
    SIGN_IN_CTA: 'typing-sign-in-cta',
  },
  AVIATION: {
    STARTER_QUESTIONS: 'aviation-starter-questions',
    STARTER_QUESTION_BUTTON: 'aviation-starter-question',
    UI_RESOURCE: 'aviation-ui-resource',
    UI_RESOURCE_IFRAME: 'aviation-ui-resource-iframe',
    UI_RESOURCE_FALLBACK: 'aviation-ui-resource-fallback',
  },
  ADMIN: {
    GITHUB_DASHBOARD: 'admin-github-dashboard',
    GITHUB_SUMMARY_CARDS: 'admin-github-summary-cards',
    GITHUB_CHARTS: 'admin-github-charts',
    GITHUB_ISSUES_TABLE: 'admin-github-issues-table',
  },
  POKER: {
    PAGE: 'poker-page',
    START_BUTTON: 'poker-start-button',
    NEXT_HAND: 'poker-next-hand',
    RESULT: 'poker-result',
    ACTION_PANEL: 'poker-action-panel',
    FOLD: 'poker-fold',
    CHECK: 'poker-check',
    CALL: 'poker-call',
    BET: 'poker-bet',
    RAISE: 'poker-raise',
    BET_SLIDER: 'poker-bet-slider',
    PERSONA_GRID: 'poker-persona-grid',
    PERSONA_OPTION: 'poker-persona-option',
    BANTER_BUBBLE: 'poker-banter-bubble',
    DECKS_PAGE: 'poker-decks-page',
    DECK_SECTION: 'poker-deck-section',
  },
  COG_PLAYGROUND: {
    MINI_COG: {
      PAGE: 'cog-playground-mini-cog-page',
      DISCLAIMER_BANNER: 'cog-playground-mini-cog-disclaimer-banner',
      START_BUTTON: 'cog-playground-mini-cog-start-button',
      CONSENT_CHECKBOX: 'cog-playground-mini-cog-consent-checkbox',
      WORD_PRESENT: 'cog-playground-mini-cog-word-present',
      REGISTRATION_INPUT: 'cog-playground-mini-cog-registration-input',
      REGISTRATION_SUBMIT: 'cog-playground-mini-cog-registration-submit',
      CLOCK_CANVAS: 'cog-playground-mini-cog-clock-canvas',
      CLOCK_CLEAR: 'cog-playground-mini-cog-clock-clear',
      CLOCK_DRAW_TOGGLE: 'cog-playground-mini-cog-clock-draw-toggle',
      CLOCK_ERASE_TOGGLE: 'cog-playground-mini-cog-clock-erase-toggle',
      CLOCK_SUBMIT: 'cog-playground-mini-cog-clock-submit',
      RECALL_INPUT: 'cog-playground-mini-cog-recall-input',
      RECALL_SUBMIT: 'cog-playground-mini-cog-recall-submit',
      RESULT: 'cog-playground-mini-cog-result',
      RESULT_SCORE: 'cog-playground-mini-cog-result-score',
      RESULT_RECALL_SOURCE: 'cog-playground-mini-cog-result-recall-source',
      RESULT_CLOCK_SOURCE: 'cog-playground-mini-cog-result-clock-source',
      RESULT_CLOCK_IMAGE: 'cog-playground-mini-cog-result-clock-image',
      RESULT_CLOCK_DOWNLOAD: 'cog-playground-mini-cog-result-clock-download',
      RESTART_BUTTON: 'cog-playground-mini-cog-restart-button',
    },
    COMPOSED: {
      PAGE: 'cog-playground-composed-page',
      DISCLAIMER_BANNER: 'cog-playground-composed-disclaimer-banner',
      CONSENT_CHECKBOX: 'cog-playground-composed-consent-checkbox',
      START_BUTTON: 'cog-playground-composed-start-button',
      WORD_PRESENT: 'cog-playground-composed-word-present',
      WORD_PRESENT_CONTINUE: 'cog-playground-composed-word-present-continue',
      ORIENTATION_DATE: 'cog-playground-composed-orientation-date',
      ORIENTATION_PLACE: 'cog-playground-composed-orientation-place',
      ORIENTATION_SUBMIT: 'cog-playground-composed-orientation-submit',
      FLUENCY_START: 'cog-playground-composed-fluency-start',
      FLUENCY_INPUT: 'cog-playground-composed-fluency-input',
      FLUENCY_SUBMIT: 'cog-playground-composed-fluency-submit',
      CLOCK_CANVAS: 'cog-playground-composed-clock-canvas',
      CLOCK_DRAW_TOGGLE: 'cog-playground-composed-clock-draw-toggle',
      CLOCK_ERASE_TOGGLE: 'cog-playground-composed-clock-erase-toggle',
      CLOCK_CLEAR: 'cog-playground-composed-clock-clear',
      CLOCK_SUBMIT: 'cog-playground-composed-clock-submit',
      DIGIT_SPAN_INPUT: 'cog-playground-composed-digit-span-input',
      DIGIT_SPAN_SUBMIT: 'cog-playground-composed-digit-span-submit',
      DIGIT_SPAN_SKIP: 'cog-playground-composed-digit-span-skip',
      RECALL_INPUT: 'cog-playground-composed-recall-input',
      RECALL_SUBMIT: 'cog-playground-composed-recall-submit',
      RESULT: 'cog-playground-composed-result',
      RESULT_SCORE: 'cog-playground-composed-result-score',
      RESTART_BUTTON: 'cog-playground-composed-restart-button',
    },
    MINI_ACE: {
      PAGE: 'cog-playground-mini-ace-page',
      DISCLAIMER_BANNER: 'cog-playground-mini-ace-disclaimer-banner',
      CONSENT_CHECKBOX: 'cog-playground-mini-ace-consent-checkbox',
      START_BUTTON: 'cog-playground-mini-ace-start-button',
      REGISTRATION_WORDS: 'cog-playground-mini-ace-registration-words',
      REGISTRATION_PRESENT_CONTINUE: 'cog-playground-mini-ace-registration-present-continue',
      REGISTRATION_INPUT: 'cog-playground-mini-ace-registration-input',
      REGISTRATION_SUBMIT: 'cog-playground-mini-ace-registration-submit',
      TIME_DAY_OF_WEEK: 'cog-playground-mini-ace-time-day-of-week',
      TIME_DATE: 'cog-playground-mini-ace-time-date',
      TIME_SEASON: 'cog-playground-mini-ace-time-season',
      TIME_SUBMIT: 'cog-playground-mini-ace-time-submit',
      ADDRESS_PRESENT: 'cog-playground-mini-ace-address-present',
      ADDRESS_PRESENT_CONTINUE: 'cog-playground-mini-ace-address-present-continue',
      FLUENCY_START: 'cog-playground-mini-ace-fluency-start',
      FLUENCY_INPUT: 'cog-playground-mini-ace-fluency-input',
      FLUENCY_SUBMIT: 'cog-playground-mini-ace-fluency-submit',
      CLOCK_CANVAS: 'cog-playground-mini-ace-clock-canvas',
      CLOCK_DRAW_TOGGLE: 'cog-playground-mini-ace-clock-draw-toggle',
      CLOCK_ERASE_TOGGLE: 'cog-playground-mini-ace-clock-erase-toggle',
      CLOCK_CLEAR: 'cog-playground-mini-ace-clock-clear',
      CLOCK_SUBMIT: 'cog-playground-mini-ace-clock-submit',
      ADDRESS_RECALL_INPUT: 'cog-playground-mini-ace-address-recall-input',
      ADDRESS_RECALL_SUBMIT: 'cog-playground-mini-ace-address-recall-submit',
      RESULT: 'cog-playground-mini-ace-result',
      RESULT_SCORE: 'cog-playground-mini-ace-result-score',
      RESTART_BUTTON: 'cog-playground-mini-ace-restart-button',
    },
  },
  SHARED: {
    MODEL_SELECT: 'model-select',
    SEARCH_BUTTON: 'search-button',
    LOADING_INDICATOR: 'loading-indicator',
  },
} as const;

// Type helper to ensure test IDs are used correctly
export type TestId =
  (typeof TEST_IDS)[keyof typeof TEST_IDS][keyof (typeof TEST_IDS)[keyof typeof TEST_IDS]];
