name: Deploy to NuxtHub
on: push

jobs:
  deploy:
  
    name: "Deploy to NuxtHub"
    runs-on: ubuntu-latest
    environment: ci # testing
    env:
      NUXT_UI_PRO_LICENSE: ${{ secrets.NUXT_UI_PRO_LICENSE }}

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        # with:
        #   version: 10 # version set in package.json

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Deploy to NuxtHub
        uses: nuxt-hub/action@v2
        with:
          directory: ./packages/blog # Path to the directory to deploy
          project-key: blog-7kvi
